CREATE VIEW VIEW_USER_INFORMATION (USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER, HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY, CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY, INSTITUTION_NAME, PROGRAM_YEAR, PROGRAM_CONCENTRATION, PROGRAM_DEGREE) 
AS SELECT CAST(U.USER_ID AS VARCHAR2(100)), U.FIRST_NAME, U.LAST_NAME, CAST(U.YEAR_OF_BIRTH AS NUMBER(38)), CAST(U.MONTH_OF_BIRTH AS NUMBER(38)), CAST(U.DAY_OF_BIRTH AS NUMBER(38)), U.GENDER, H.CITY_NAME, H.STATE_NAME, H.COUNTRY_NAME, C.CITY_NAME, C.STATE_NAME, C.COUNTRY_NAME, P.INSTITUTION, CAST(E.PROGRAM_YEAR AS NUMBER(38)), CAST(P.CONCENTRATION AS CHAR(100)), P.DEGREE
FROM USERS U
LEFT JOIN USER_HOMETOWN_CITY U1 ON U.USER_ID = U1.USER_ID
LEFT JOIN CITIES H ON U1.HOMETOWN_CITY_ID = H.CITY_ID
LEFT JOIN USER_CURRENT_CITY U2 ON U.USER_ID = U2.USER_ID
LEFT JOIN CITIES C ON U2.CURRENT_CITY_ID = C.CITY_ID
LEFT JOIN EDUCATION E ON U.USER_ID = E.USER_ID
LEFT JOIN PROGRAMS P ON  E.PROGRAM_ID = P.PROGRAM_ID;

CREATE VIEW VIEW_ARE_FRIENDS (USER1_ID, USER2_ID) AS
SELECT CAST(F.USER1_ID AS VARCHAR2(100)), CAST(F.USER2_ID AS VARCHAR2(100))
FROM FRIENDS F;

CREATE VIEW VIEW_PHOTO_INFORMATION (ALBUM_ID, ALBUM_OWNER_ID, COVER_PHOTO_ID, ALBUM_NAME, ALBUM_CREATED_TIME, ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY, PHOTO_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK) AS
SELECT A.ALBUM_ID, CAST(A.ALBUM_OWNER_ID AS VARCHAR2(100)), A.COVER_PHOTO_ID, A.ALBUM_NAME, CAST(A.ALBUM_CREATED_TIME AS TIMESTAMP(6)), CAST(A.ALBUM_MODIFIED_TIME AS TIMESTAMP(6)), A.ALBUM_LINK, A.ALBUM_VISIBILITY, P.PHOTO_ID, P.PHOTO_CAPTION, CAST(P.PHOTO_CREATED_TIME AS TIMESTAMP(6)), CAST(P.PHOTO_MODIFIED_TIME AS TIMESTAMP(6)), P.PHOTO_LINK
FROM ALBUMS A
INNER JOIN PHOTOS P ON A.ALBUM_ID = P.ALBUM_ID;

CREATE VIEW VIEW_TAG_INFORMATION (PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X, TAG_Y)
AS SELECT T.TAG_PHOTO_ID, CAST(T.TAG_SUBJECT_ID AS VARCHAR2(100)), CAST(T.TAG_CREATED_TIME AS TIMESTAMP(6)), T.TAG_X, T.TAG_Y
FROM TAGS T;

CREATE VIEW VIEW_EVENT_INFORMATION (EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE, EVENT_DESCRIPTION, EVENT_HOST, EVENT_TYPE, EVENT_SUBTYPE, EVENT_LOCATION, EVENT_CITY, EVENT_STATE, EVENT_COUNTRY, EVENT_START_TIME, EVENT_END_TIME) AS
SELECT CAST(E.EVENT_ID AS VARCHAR2(100)), CAST(E.EVENT_CREATOR_ID AS VARCHAR2(100)), E.EVENT_NAME, CAST(E.EVENT_TAGLINE AS VARCHAR2(1000)), CAST(E.EVENT_DESCRIPTION AS VARCHAR2(4000)), E.EVENT_HOST, E.EVENT_TYPE, E.EVENT_SUBTYPE, CAST(E.EVENT_LOCATION AS VARCHAR2(200)), C.CITY_NAME, C.STATE_NAME, C.COUNTRY_NAME, CAST(E.EVENT_START_TIME AS TIMESTAMP(6)), CAST(E.EVENT_END_TIME AS TIMESTAMP(6))
FROM USER_EVENTS E
LEFT JOIN CITIES C ON E.EVENT_CITY_ID = C.CITY_ID;

