INSERT INTO USERS
SELECT DISTINCT CAST(USER_ID AS NUMBER), FIRST_NAME, LAST_NAME, CAST(YEAR_OF_BIRTH AS INTEGER), CAST(MONTH_OF_BIRTH AS INTEGER), CAST(DAY_OF_BIRTH AS INTEGER), GENDER 
FROM keykholt.PUBLIC_USER_INFORMATION;

INSERT INTO FRIENDS
SELECT DISTINCT CAST(F.USER1_ID AS NUMBER), CAST(F.USER2_ID AS NUMBER) FROM keykholt.PUBLIC_ARE_FRIENDS F;


INSERT INTO CITIES(CITY_NAME,STATE_NAME,COUNTRY_NAME)
SELECT DISTINCT HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY FROM keykholt.PUBLIC_USER_INFORMATION 
UNION 
SELECT DISTINCT CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY FROM keykholt.PUBLIC_USER_INFORMATION 
UNION 
SELECT DISTINCT EVENT_CITY, EVENT_STATE, EVENT_COUNTRY FROM keykholt.PUBLIC_EVENT_INFORMATION; 

INSERT INTO USER_CURRENT_CITY
SELECT DISTINCT C.USER_ID,CITY_ID
FROM keykholt.PUBLIC_USER_INFORMATION C, CITIES, USERS
WHERE USERS.USER_ID = C.USER_ID AND C.CURRENT_CITY = CITIES.CITY_NAME AND C.CURRENT_STATE = CITIES.STATE_NAME AND C.CURRENT_COUNTRY = CITIES.COUNTRY_NAME;

INSERT INTO USER_HOMETOWN_CITY
SELECT DISTINCT H.USER_ID,CITY_ID
FROM keykholt.PUBLIC_USER_INFORMATION H, CITIES, USERS
WHERE USERS.USER_ID = H.USER_ID AND H.HOMETOWN_CITY = CITIES.CITY_NAME AND H.HOMETOWN_STATE = CITIES.STATE_NAME AND H.HOMETOWN_COUNTRY = CITIES.COUNTRY_NAME;

INSERT INTO PROGRAMS(INSTITUTION,CONCENTRATION,DEGREE)
SELECT DISTINCT INSTITUTION_NAME,CAST(PROGRAM_CONCENTRATION AS VARCHAR2(100)),PROGRAM_DEGREE
FROM keykholt.PUBLIC_USER_INFORMATION;

INSERT INTO EDUCATION
SELECT DISTINCT CAST(E.USER_ID AS NUMBER),PROGRAM_ID,CAST(PROGRAM_YEAR AS INTEGER)
FROM keykholt.PUBLIC_USER_INFORMATION E, PROGRAMS, USERS
WHERE USERS.USER_ID = E.USER_ID AND E.INSTITUTION_NAME = PROGRAMS.INSTITUTION AND E.PROGRAM_CONCENTRATION = PROGRAMS.CONCENTRATION AND E.PROGRAM_DEGREE = PROGRAMS.DEGREE;

INSERT INTO USER_EVENTS 
SELECT DISTINCT CAST(EVENT_ID AS NUMBER),CAST(EVENT_CREATOR_ID AS NUMBER),EVENT_NAME,CAST(EVENT_TAGLINE AS VARCHAR2(100)),CAST(EVENT_DESCRIPTION AS VARCHAR2(100)),EVENT_HOST,EVENT_TYPE,EVENT_SUBTYPE,CAST(EVENT_LOCATION AS VARCHAR2(100)),CITY_ID,CAST(EVENT_START_TIME AS TIMESTAMP),CAST(EVENT_END_TIME AS TIMESTAMP)
FROM keykholt.PUBLIC_EVENT_INFORMATION LEFT JOIN CITIES
ON (keykholt.PUBLIC_EVENT_INFORMATION.EVENT_CITY = CITIES.CITY_NAME OR (keykholt.PUBLIC_EVENT_INFORMATION.EVENT_CITY = NULL AND CITIES.CITY_NAME = NULL));

INSERT INTO ALBUMS
SELECT DISTINCT ALBUM_ID,CAST(OWNER_ID AS NUMBER),ALBUM_NAME,CAST(ALBUM_CREATED_TIME AS TIMESTAMP),CAST(ALBUM_MODIFIED_TIME AS TIMESTAMP),ALBUM_LINK,ALBUM_VISIBILITY,COVER_PHOTO_ID
FROM keykholt.PUBLIC_PHOTO_INFORMATION;


INSERT INTO PHOTOS
SELECT DISTINCT PHOTO_ID,ALBUM_ID,PHOTO_CAPTION,CAST(PHOTO_CREATED_TIME AS TIMESTAMP),CAST(PHOTO_MODIFIED_TIME AS TIMESTAMP),PHOTO_LINK
FROM keykholt.PUBLIC_PHOTO_INFORMATION;

INSERT INTO TAGS
SELECT DISTINCT PHOTO_ID,CAST(TAG_SUBJECT_ID AS NUMBER),CAST(TAG_CREATED_TIME AS TIMESTAMP),TAG_X_COORDINATE,TAG_Y_COORDINATE
FROM keykholt.PUBLIC_TAG_INFORMATION;









